# permissions for end users to view gates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gate-controller
    app.kubernetes.io/part-of: gate-controller
    app.kubernetes.io/managed-by: kustomize
  name: gate-viewer-role
rules:
- apiGroups:
  - gating.toolkit.fluxcd.io
  resources:
  - gates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gating.toolkit.fluxcd.io
  resources:
  - gates/status
  verbs:
  - get
