---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gating.toolkit.fluxcd.io
  resources:
  - gates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gating.toolkit.fluxcd.io
  resources:
  - gates/finalizers
  verbs:
  - update
- apiGroups:
  - gating.toolkit.fluxcd.io
  resources:
  - gates/status
  verbs:
  - get
  - patch
  - update
